### ISSUE TITLE
default db unreachable by voodoo

### ISSUE THREAD

**Issue by bealdav** [akretion/voodoo#69] opened 2017-02-06 18:22 UTC
Name: voodoo-cli
Version: 2.4.0

Linux Image: latest at created date

============

## To reproduce

1. voodoo new with v8 project
2. voodoo run
3. ak build
4. ak run
5. go to http://localhost:8069

## expected
odoo directly connected to db database

## real situation
redirect to http://localhost:8069/web/database/manager#action=database_manager
because `db` not reachable
db database existing but unreachable by odoo
```
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-----------+----------+----------+------------+------------+-----------------------
 db        | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
```

**Comment by rvalyi** [comment] 2017-02-20 06:54
I think this is a duplicate of https://github.com/akretion/voodoo/issues/50

**Closed by rvalyi** 2017-02-20 06:54 UTC
